### ISSUE TITLE
addd github wiki directly to the website 

### ISSUE THREAD

**Issue by Tusharvoid** [python-telegram-bot/python-telegram-bot.github.io#20]
rather than going to GitHub add wiki to the website so that user can read directly

**Comment by Poolitzer** [comment]
Hi. What upside would that have to you?

**Comment by Poolitzer** [comment]
Hi. What upside would that have to you?

**Comment by voidninjaaa-panda** [comment]
No just suggestions it would be better

**Comment by Poolitzer** [comment]
How/why would it be better though?

**Comment by voidninjaaa-panda** [comment]
Integrating the wiki directly into your website instead of redirecting to GitHub has several advantages. It provides a centralized, branded experience with easier navigation, better control over access, and seamless integration with other content on your site. This approach enhances the overall user experience and allows for better version control, analytics, and user feedback.

**Comment by Poolitzer** [comment]
Your reply reads like you generated it with a LLM. I sure hope that's not the case, but if the next one gives the same unassociated vibes, I will close this issue as you seemingly can't be bothered to have your own thoughts about this

> It provides a centralized, branded experience

Centralized, ok. But we don't care about brands. RTD is also not our brand, it's an often used theme we use there. And our own website has absolutely no brand theming whatsoever, the CSS is like 300 lines long.

> with easier navigation, 

Please tell me how exactly we can make the navigation easier.

> better control over access

Anyone can have access.

>and seamless integration with other content on your site. 

I would argue the content on our actual site, not the docs, have no integration need whatsoever. And neither is there more integration to docs needed imo, we link wherever applicable. Where can you see better integration?

Or do you mean seamless because the domain would stay the same. Which I would vote to not be worth any hassle to change. An end user shouldn't really care about a domain change.

> This approach enhances the overall user experience

Okay this is a totally empty statement.


> and allows for better version control


There is no better version control then git in this situation imo

> analytics

Over my dead body we include analytics

> and user feedback.

I love issues for this, they forster fruitful discussion. What kind of different feedback are you thinking about.
